/*
 * This file is generated by jOOQ.
 */
package app.rutherford.database.jooq.tables.pojos


import java.io.Serializable
import java.time.Instant
import java.util.UUID

import javax.annotation.processing.Generated


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.17.6",
        "schema version:public_1"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
data class JAuthUserRefreshToken(
    var id: UUID? = null,
    var createdAt: Instant? = null,
    var updatedAt: Instant? = null,
    var expiration: Instant? = null,
    var state: String? = null,
    var tokenHash: String? = null,
    var userId: UUID? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other === null)
            return false
        if (this::class != other::class)
            return false
        val o: JAuthUserRefreshToken = other as JAuthUserRefreshToken
        if (this.id === null) {
            if (o.id !== null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.createdAt === null) {
            if (o.createdAt !== null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt === null) {
            if (o.updatedAt !== null)
                return false
        }
        else if (this.updatedAt != o.updatedAt)
            return false
        if (this.expiration === null) {
            if (o.expiration !== null)
                return false
        }
        else if (this.expiration != o.expiration)
            return false
        if (this.state === null) {
            if (o.state !== null)
                return false
        }
        else if (this.state != o.state)
            return false
        if (this.tokenHash === null) {
            if (o.tokenHash !== null)
                return false
        }
        else if (this.tokenHash != o.tokenHash)
            return false
        if (this.userId === null) {
            if (o.userId !== null)
                return false
        }
        else if (this.userId != o.userId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id === null) 0 else this.id.hashCode())
        result = prime * result + (if (this.createdAt === null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.updatedAt === null) 0 else this.updatedAt.hashCode())
        result = prime * result + (if (this.expiration === null) 0 else this.expiration.hashCode())
        result = prime * result + (if (this.state === null) 0 else this.state.hashCode())
        result = prime * result + (if (this.tokenHash === null) 0 else this.tokenHash.hashCode())
        result = prime * result + (if (this.userId === null) 0 else this.userId.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("JAuthUserRefreshToken (")

        sb.append(id)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)
        sb.append(", ").append(expiration)
        sb.append(", ").append(state)
        sb.append(", ").append(tokenHash)
        sb.append(", ").append(userId)

        sb.append(")")
        return sb.toString()
    }
}
