/*
 * This file is generated by jOOQ.
 */
package app.rutherford.database.jooq.tables.references


import app.rutherford.database.jooq.tables.AuthUser
import app.rutherford.database.jooq.tables.AuthUserRefreshToken



/**
 * The table <code>public.auth_user</code>.
 */
val AUTH_USER: AuthUser = AuthUser.AUTH_USER

/**
 * The table <code>public.auth_user_refresh_token</code>.
 */
val AUTH_USER_REFRESH_TOKEN: AuthUserRefreshToken = AuthUserRefreshToken.AUTH_USER_REFRESH_TOKEN
