/*
 * This file is generated by jOOQ.
 */
package app.rutherford.database.schema.tables;


import app.rutherford.database.converter.InstantConverter;
import app.rutherford.database.schema.Indexes;
import app.rutherford.database.schema.Keys;
import app.rutherford.database.schema.Public;
import app.rutherford.database.schema.tables.records.AuthUserRefreshTokenRecord;

import java.time.Instant;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6",
        "schema version:public_1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthUserRefreshToken extends TableImpl<AuthUserRefreshTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.auth_user_refresh_token</code>
     */
    public static final AuthUserRefreshToken AUTH_USER_REFRESH_TOKEN = new AuthUserRefreshToken();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthUserRefreshTokenRecord> getRecordType() {
        return AuthUserRefreshTokenRecord.class;
    }

    /**
     * The column <code>public.auth_user_refresh_token.id</code>.
     */
    public final TableField<AuthUserRefreshTokenRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.auth_user_refresh_token.created_at</code>.
     */
    public final TableField<AuthUserRefreshTokenRecord, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMP(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.TIMESTAMP)), this, "", new InstantConverter());

    /**
     * The column <code>public.auth_user_refresh_token.updated_at</code>.
     */
    public final TableField<AuthUserRefreshTokenRecord, Instant> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMP(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.TIMESTAMP)), this, "", new InstantConverter());

    /**
     * The column <code>public.auth_user_refresh_token.expiration</code>.
     */
    public final TableField<AuthUserRefreshTokenRecord, Instant> EXPIRATION = createField(DSL.name("expiration"), SQLDataType.TIMESTAMP(6), this, "", new InstantConverter());

    /**
     * The column <code>public.auth_user_refresh_token.state</code>.
     */
    public final TableField<AuthUserRefreshTokenRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.auth_user_refresh_token.token_hash</code>.
     */
    public final TableField<AuthUserRefreshTokenRecord, String> TOKEN_HASH = createField(DSL.name("token_hash"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.auth_user_refresh_token.user_id</code>.
     */
    public final TableField<AuthUserRefreshTokenRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID, this, "");

    private AuthUserRefreshToken(Name alias, Table<AuthUserRefreshTokenRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthUserRefreshToken(Name alias, Table<AuthUserRefreshTokenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.auth_user_refresh_token</code> table
     * reference
     */
    public AuthUserRefreshToken(String alias) {
        this(DSL.name(alias), AUTH_USER_REFRESH_TOKEN);
    }

    /**
     * Create an aliased <code>public.auth_user_refresh_token</code> table
     * reference
     */
    public AuthUserRefreshToken(Name alias) {
        this(alias, AUTH_USER_REFRESH_TOKEN);
    }

    /**
     * Create a <code>public.auth_user_refresh_token</code> table reference
     */
    public AuthUserRefreshToken() {
        this(DSL.name("auth_user_refresh_token"), null);
    }

    public <O extends Record> AuthUserRefreshToken(Table<O> child, ForeignKey<O, AuthUserRefreshTokenRecord> key) {
        super(child, key, AUTH_USER_REFRESH_TOKEN);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.USER_REFRESH_TOKENS_TOKEN_HASH_IDX);
    }

    @Override
    public UniqueKey<AuthUserRefreshTokenRecord> getPrimaryKey() {
        return Keys.AUTH_USER_REFRESH_TOKEN_PKEY;
    }

    @Override
    public List<ForeignKey<AuthUserRefreshTokenRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AUTH_USER_REFRESH_TOKEN__AUTH_USER_REFRESH_TOKEN_USER_ID_FKEY);
    }

    private transient AuthUser _authUser;

    /**
     * Get the implicit join path to the <code>public.auth_user</code> table.
     */
    public AuthUser authUser() {
        if (_authUser == null)
            _authUser = new AuthUser(this, Keys.AUTH_USER_REFRESH_TOKEN__AUTH_USER_REFRESH_TOKEN_USER_ID_FKEY);

        return _authUser;
    }

    @Override
    public AuthUserRefreshToken as(String alias) {
        return new AuthUserRefreshToken(DSL.name(alias), this);
    }

    @Override
    public AuthUserRefreshToken as(Name alias) {
        return new AuthUserRefreshToken(alias, this);
    }

    @Override
    public AuthUserRefreshToken as(Table<?> alias) {
        return new AuthUserRefreshToken(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserRefreshToken rename(String name) {
        return new AuthUserRefreshToken(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserRefreshToken rename(Name name) {
        return new AuthUserRefreshToken(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserRefreshToken rename(Table<?> name) {
        return new AuthUserRefreshToken(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, Instant, Instant, Instant, String, String, UUID> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super UUID, ? super Instant, ? super Instant, ? super Instant, ? super String, ? super String, ? super UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super UUID, ? super Instant, ? super Instant, ? super Instant, ? super String, ? super String, ? super UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
