/*
 * This file is generated by jOOQ.
 */
package app.rutherford.database.schema.tables.records;


import app.rutherford.database.schema.tables.AuthUserRefreshToken;

import java.time.Instant;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6",
        "schema version:public_1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthUserRefreshTokenRecord extends UpdatableRecordImpl<AuthUserRefreshTokenRecord> implements Record7<UUID, Instant, Instant, Instant, String, String, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.auth_user_refresh_token.id</code>.
     */
    public AuthUserRefreshTokenRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.auth_user_refresh_token.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.auth_user_refresh_token.created_at</code>.
     */
    public AuthUserRefreshTokenRecord setCreatedAt(Instant value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.auth_user_refresh_token.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(1);
    }

    /**
     * Setter for <code>public.auth_user_refresh_token.updated_at</code>.
     */
    public AuthUserRefreshTokenRecord setUpdatedAt(Instant value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.auth_user_refresh_token.updated_at</code>.
     */
    public Instant getUpdatedAt() {
        return (Instant) get(2);
    }

    /**
     * Setter for <code>public.auth_user_refresh_token.expiration</code>.
     */
    public AuthUserRefreshTokenRecord setExpiration(Instant value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.auth_user_refresh_token.expiration</code>.
     */
    public Instant getExpiration() {
        return (Instant) get(3);
    }

    /**
     * Setter for <code>public.auth_user_refresh_token.state</code>.
     */
    public AuthUserRefreshTokenRecord setState(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.auth_user_refresh_token.state</code>.
     */
    public String getState() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.auth_user_refresh_token.token_hash</code>.
     */
    public AuthUserRefreshTokenRecord setTokenHash(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.auth_user_refresh_token.token_hash</code>.
     */
    public String getTokenHash() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.auth_user_refresh_token.user_id</code>.
     */
    public AuthUserRefreshTokenRecord setUserId(UUID value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.auth_user_refresh_token.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, Instant, Instant, Instant, String, String, UUID> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UUID, Instant, Instant, Instant, String, String, UUID> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AuthUserRefreshToken.AUTH_USER_REFRESH_TOKEN.ID;
    }

    @Override
    public Field<Instant> field2() {
        return AuthUserRefreshToken.AUTH_USER_REFRESH_TOKEN.CREATED_AT;
    }

    @Override
    public Field<Instant> field3() {
        return AuthUserRefreshToken.AUTH_USER_REFRESH_TOKEN.UPDATED_AT;
    }

    @Override
    public Field<Instant> field4() {
        return AuthUserRefreshToken.AUTH_USER_REFRESH_TOKEN.EXPIRATION;
    }

    @Override
    public Field<String> field5() {
        return AuthUserRefreshToken.AUTH_USER_REFRESH_TOKEN.STATE;
    }

    @Override
    public Field<String> field6() {
        return AuthUserRefreshToken.AUTH_USER_REFRESH_TOKEN.TOKEN_HASH;
    }

    @Override
    public Field<UUID> field7() {
        return AuthUserRefreshToken.AUTH_USER_REFRESH_TOKEN.USER_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public Instant component2() {
        return getCreatedAt();
    }

    @Override
    public Instant component3() {
        return getUpdatedAt();
    }

    @Override
    public Instant component4() {
        return getExpiration();
    }

    @Override
    public String component5() {
        return getState();
    }

    @Override
    public String component6() {
        return getTokenHash();
    }

    @Override
    public UUID component7() {
        return getUserId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public Instant value2() {
        return getCreatedAt();
    }

    @Override
    public Instant value3() {
        return getUpdatedAt();
    }

    @Override
    public Instant value4() {
        return getExpiration();
    }

    @Override
    public String value5() {
        return getState();
    }

    @Override
    public String value6() {
        return getTokenHash();
    }

    @Override
    public UUID value7() {
        return getUserId();
    }

    @Override
    public AuthUserRefreshTokenRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public AuthUserRefreshTokenRecord value2(Instant value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AuthUserRefreshTokenRecord value3(Instant value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public AuthUserRefreshTokenRecord value4(Instant value) {
        setExpiration(value);
        return this;
    }

    @Override
    public AuthUserRefreshTokenRecord value5(String value) {
        setState(value);
        return this;
    }

    @Override
    public AuthUserRefreshTokenRecord value6(String value) {
        setTokenHash(value);
        return this;
    }

    @Override
    public AuthUserRefreshTokenRecord value7(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public AuthUserRefreshTokenRecord values(UUID value1, Instant value2, Instant value3, Instant value4, String value5, String value6, UUID value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthUserRefreshTokenRecord
     */
    public AuthUserRefreshTokenRecord() {
        super(AuthUserRefreshToken.AUTH_USER_REFRESH_TOKEN);
    }

    /**
     * Create a detached, initialised AuthUserRefreshTokenRecord
     */
    public AuthUserRefreshTokenRecord(UUID id, Instant createdAt, Instant updatedAt, Instant expiration, String state, String tokenHash, UUID userId) {
        super(AuthUserRefreshToken.AUTH_USER_REFRESH_TOKEN);

        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setExpiration(expiration);
        setState(state);
        setTokenHash(tokenHash);
        setUserId(userId);
    }

    /**
     * Create a detached, initialised AuthUserRefreshTokenRecord
     */
    public AuthUserRefreshTokenRecord(app.rutherford.database.schema.tables.pojos.AuthUserRefreshToken value) {
        super(AuthUserRefreshToken.AUTH_USER_REFRESH_TOKEN);

        if (value != null) {
            setId(value.getId());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setExpiration(value.getExpiration());
            setState(value.getState());
            setTokenHash(value.getTokenHash());
            setUserId(value.getUserId());
        }
    }
}
