/*
 * This file is generated by jOOQ.
 */
package app.rutherford.database.jooq.indexes


import app.rutherford.database.jooq.tables.AuthUserRefreshToken

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val USER_REFRESH_TOKENS_TOKEN_HASH_IDX: Index = Internal.createIndex(DSL.name("user_refresh_tokens_token_hash_idx"), AuthUserRefreshToken.AUTH_USER_REFRESH_TOKEN, arrayOf(AuthUserRefreshToken.AUTH_USER_REFRESH_TOKEN.TOKEN_HASH), false)
