/*
 * This file is generated by jOOQ.
 */
package app.rutherford.database.schema.tables.daos;


import app.rutherford.database.schema.tables.Users;
import app.rutherford.database.schema.tables.records.UsersRecord;

import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6",
        "schema version:public_1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersDao extends DAOImpl<UsersRecord, app.rutherford.database.schema.tables.pojos.Users, UUID> {

    /**
     * Create a new UsersDao without any configuration
     */
    public UsersDao() {
        super(Users.USERS, app.rutherford.database.schema.tables.pojos.Users.class);
    }

    /**
     * Create a new UsersDao with an attached configuration
     */
    public UsersDao(Configuration configuration) {
        super(Users.USERS, app.rutherford.database.schema.tables.pojos.Users.class, configuration);
    }

    @Override
    public UUID getId(app.rutherford.database.schema.tables.pojos.Users object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<app.rutherford.database.schema.tables.pojos.Users> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Users.USERS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<app.rutherford.database.schema.tables.pojos.Users> fetchById(UUID... values) {
        return fetch(Users.USERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public app.rutherford.database.schema.tables.pojos.Users fetchOneById(UUID value) {
        return fetchOne(Users.USERS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<app.rutherford.database.schema.tables.pojos.Users> fetchOptionalById(UUID value) {
        return fetchOptional(Users.USERS.ID, value);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<app.rutherford.database.schema.tables.pojos.Users> fetchRangeOfCreatedAt(Instant lowerInclusive, Instant upperInclusive) {
        return fetchRange(Users.USERS.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<app.rutherford.database.schema.tables.pojos.Users> fetchByCreatedAt(Instant... values) {
        return fetch(Users.USERS.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<app.rutherford.database.schema.tables.pojos.Users> fetchRangeOfUpdatedAt(Instant lowerInclusive, Instant upperInclusive) {
        return fetchRange(Users.USERS.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<app.rutherford.database.schema.tables.pojos.Users> fetchByUpdatedAt(Instant... values) {
        return fetch(Users.USERS.UPDATED_AT, values);
    }

    /**
     * Fetch records that have <code>last_login BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<app.rutherford.database.schema.tables.pojos.Users> fetchRangeOfLastLogin(Instant lowerInclusive, Instant upperInclusive) {
        return fetchRange(Users.USERS.LAST_LOGIN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_login IN (values)</code>
     */
    public List<app.rutherford.database.schema.tables.pojos.Users> fetchByLastLogin(Instant... values) {
        return fetch(Users.USERS.LAST_LOGIN, values);
    }

    /**
     * Fetch records that have <code>application_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<app.rutherford.database.schema.tables.pojos.Users> fetchRangeOfApplicationName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Users.USERS.APPLICATION_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>application_name IN (values)</code>
     */
    public List<app.rutherford.database.schema.tables.pojos.Users> fetchByApplicationName(String... values) {
        return fetch(Users.USERS.APPLICATION_NAME, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<app.rutherford.database.schema.tables.pojos.Users> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(Users.USERS.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<app.rutherford.database.schema.tables.pojos.Users> fetchByEmail(String... values) {
        return fetch(Users.USERS.EMAIL, values);
    }

    /**
     * Fetch records that have <code>email_confirmed BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<app.rutherford.database.schema.tables.pojos.Users> fetchRangeOfEmailConfirmed(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Users.USERS.EMAIL_CONFIRMED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email_confirmed IN (values)</code>
     */
    public List<app.rutherford.database.schema.tables.pojos.Users> fetchByEmailConfirmed(Boolean... values) {
        return fetch(Users.USERS.EMAIL_CONFIRMED, values);
    }

    /**
     * Fetch records that have <code>password_hash BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<app.rutherford.database.schema.tables.pojos.Users> fetchRangeOfPasswordHash(String lowerInclusive, String upperInclusive) {
        return fetchRange(Users.USERS.PASSWORD_HASH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>password_hash IN (values)</code>
     */
    public List<app.rutherford.database.schema.tables.pojos.Users> fetchByPasswordHash(String... values) {
        return fetch(Users.USERS.PASSWORD_HASH, values);
    }
}
