/*
 * This file is generated by jOOQ.
 */
package app.rutherford.database.schema;


import app.rutherford.database.schema.tables.AuthUser;
import app.rutherford.database.schema.tables.AuthUserRefreshToken;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6",
        "schema version:public_1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.auth_user</code>.
     */
    public final AuthUser AUTH_USER = AuthUser.AUTH_USER;

    /**
     * The table <code>public.auth_user_refresh_token</code>.
     */
    public final AuthUserRefreshToken AUTH_USER_REFRESH_TOKEN = AuthUserRefreshToken.AUTH_USER_REFRESH_TOKEN;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AuthUser.AUTH_USER,
            AuthUserRefreshToken.AUTH_USER_REFRESH_TOKEN
        );
    }
}
