/*
 * This file is generated by jOOQ.
 */
package app.rutherford.database.schema;


import app.rutherford.database.schema.tables.UserRefreshTokens;
import app.rutherford.database.schema.tables.Users;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6",
        "schema version:public_1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.user_refresh_tokens</code>.
     */
    public static final UserRefreshTokens USER_REFRESH_TOKENS = UserRefreshTokens.USER_REFRESH_TOKENS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
